---

dataset:
  var_path: "../../datasets/TrnavaZilina/VAR/clips"
  main_path: "../dp_autocam/recordings/2023-10-28/clips"
masks_output_dir: "tmp"

export_every_x_seconds: 10 # Time interval to export a warped frame.
pitch_overlay: true # Overlay the pitch model scheme on the exported frame.


image_size:
  - 1280
  - 720