---

dataset:
  var_path: "../../datasets/TrnavaZilina/VAR/full"
  main_path: "../dp_autocam/recordings/2023-10-29/full"
masks_output_dir: "tmp"

export_every_x_seconds: 1 # Time interval to export a warped frame.
pitch_overlay: false # Overlay the pitch model scheme on the exported frame.


image_size:
  - 1280
  - 720