---

dataset:
  var_path: "../../datasets/TrnavaZilina/VAR/clips"
  # main_path: "../dp_autocam/recordings/single-detector/clips"
  main_path: "../../../output_footage/single_detector/clips"
masks_output_dir: "tmp"

export_every_x_seconds: 1 # Time interval to export a warped frame.
pitch_overlay: false # Overlay the pitch model scheme on the exported frame.


image_size:
  - 1280
  - 720